const GET_PRODUCT = 'GET_PRODUCT';
const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export {
  GET_PRODUCT_FAIL,
  GET_PRODUCT_SUCCESS,
  GET_PRODUCT,
}